#!/bin/bash
ffmpeg -loglevel quiet -y -f x11grab -video_size 1900x1080 -i $DISPLAY -i ~/.config/i3/fancy-multimonitor/lock.png -filter_complex "boxblur=5:1,overlay=(main_w-overlay_w-10):(main_h-overlay_h-10)" -vframes 1  /tmp/i3lock.png
i3lock -i /tmp/i3lock.png -t
rm /tmp/i3lock.png
